"use client";
import { useCallback, useEffect, useRef, useState } from 'react';
import { CdSelect } from '@/components/cdash/CdField';
import { CdHelp } from '@/components/cdash/CdHelp';
import { readGroupConflict, safeGroupIssues, type GroupConflictDiagnostics } from '@/lib/finance/supply-group-diagnostics';
import type { SupplyGroupDraft, SupplyGroupRecord, SupplyGroupPreview, SupplyGroupRef, SupplyGroupRegion, SupplyGroupEvidenceDiagnostics } from '@/lib/finance/supply-group-types';
import type { SupplyReviewRecord } from '@/lib/finance/supply-review-types';
import { validateGroupPreviewInput } from '@/lib/finance/supply-group-pure';
import type { PdfMetadata } from '@/lib/finance/supply-group-pdf';

const API='/api/finance/supply-group-reviews', EVIDENCE='/api/finance/supply-group-evidence', DOCUMENTS='/api/finance/supply-documents';
type DocumentRow={documentId:string;portionId:string;latestObservation:{approvalNumber:string|null;date:string;supply:number;tax:number;total:number}};
type Observation={observationId:string;version:number;summary:{date:string;total:number}};
type EvidenceRow={documentId:string;evidenceHash:string;fileName:string;contentType?:string};
type Draft=Omit<SupplyGroupDraft,'coverageConfirmed'>&{coverageConfirmed:boolean};
type Pending={endpoint:string;action:'register'|'verify'|'withdraw';body:Record<string,unknown>};
type List={records:SupplyGroupRecord[];hasMore:boolean;nextCursor:string|null;canManage:boolean};
const checkedList=(v:List)=>{if(!v||!Array.isArray(v.records)||typeof v.hasMore!=='boolean'||v.hasMore!==(typeof v.nextCursor==='string'&&v.nextCursor.length>0)||!v.hasMore&&v.nextCursor!==null)throw Error('목록 페이지를 확인할 수 없습니다.');return v;};
const relationKey=(d:Draft)=>JSON.stringify([d.singleton.portionId,[...d.members.map(m=>m.portionId)].sort()]);
const blankRef=():SupplyGroupRef=>({documentId:'',portionId:'',observationId:''});
const blank=(subjectId:string):Draft=>({subjectId,reviewRevisionId:'',singleton:blankRef(),members:[blankRef(),blankRef()],evidenceManifestId:'',reason:'',currencyEvidence:[],coverageConfirmed:false});
const normalized=(v:unknown):string=>v===null||typeof v!=='object'?JSON.stringify(v):Array.isArray(v)?`[${v.map(normalized).join(',')}]`:`{${Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+normalized((v as Record<string,unknown>)[k])).join(',')}}`;
const money=(n:number)=>Number.isSafeInteger(n)?`${n.toLocaleString('ko-KR')}원`:'확인 필요';
class ApiError extends Error{constructor(message:string,readonly status:number,readonly diagnostic:GroupConflictDiagnostics|null){super(message);}}
async function json(url:string,body?:Record<string,unknown>){
  const r=await fetch(url,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{cache:'no-store'});
  const v=await r.json();if(!r.ok){const d=readGroupConflict(v,r.status);throw new ApiError(d?.error||(r.status===409?'현재 근거와 최신 확인판을 다시 확인하세요.':v?.error)||`요청을 처리하지 못했습니다 (${r.status}).`,r.status,d);}return v;
}
const query=(subjectId:string,extra:Record<string,string>={})=>new URLSearchParams({subjectId,...extra}).toString();
const state=(v:SupplyGroupRecord)=>v.state==='withdrawn'?'철회':'전체 대응 확인';

export function SupplyGroupReviewPanel({subjectId,canManage:parentManage}:{subjectId:string;canManage:boolean}){
  const [draft,setDraft]=useState<Draft>(()=>blank(subjectId)),[original,setOriginal]=useState<SupplyGroupRecord|null>(null);
  const [records,setRecords]=useState<SupplyGroupRecord[]>([]),[history,setHistory]=useState<SupplyGroupRecord[]>([]),[hasMore,setHasMore]=useState(false),[historyMore,setHistoryMore]=useState(false);
  const [basis,setBasis]=useState<SupplyReviewRecord[]>([]),[documents,setDocuments]=useState<DocumentRow[]>([]),[evidence,setEvidence]=useState<EvidenceRow[]>([]),[documentsMore,setDocumentsMore]=useState(false);
  const [caseCursor,setCaseCursor]=useState<string|null>(null),[historyCursor,setHistoryCursor]=useState<string|null>(null);
  const [evidenceDiagnostics,setEvidenceDiagnostics]=useState<SupplyGroupEvidenceDiagnostics|null>(null),[evidenceDiagnosticError,setEvidenceDiagnosticError]=useState('');
  const caseList=useRef<HTMLElement|null>(null);
  const [documentCursor,setDocumentCursor]=useState<string|null>(null);
  const [observations,setObservations]=useState<Record<string,Observation[]>>({}),[manage,setManage]=useState(false),[healthy,setHealthy]=useState(false);
  const [evidenceId,setEvidenceId]=useState(''),[metadata,setMetadata]=useState<PdfMetadata|null>(null),[page,setPage]=useState(1),[image,setImage]=useState(''),[imageReady,setImageReady]=useState(false);
  const [regions,setRegions]=useState<SupplyGroupRegion[]>([]),[selectedRegion,setSelectedRegion]=useState('');
  const [preview,setPreview]=useState<SupplyGroupPreview|null>(null),[withdrawReason,setWithdrawReason]=useState('');
  const [error,setError]=useState(''),[diagnostic,setDiagnostic]=useState<GroupConflictDiagnostics|null>(null),[errorStatus,setErrorStatus]=useState<number|null>(null),[notice,setNotice]=useState('');
  const [busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[uncertain,setUncertain]=useState(false);
  const pending=useRef<Pending|null>(null),inFlight=useRef(false),scope=useRef(subjectId),epoch=useRef(0),drag=useRef<{x:number;y:number}|null>(null);
  scope.current=subjectId;
  const canManage=parentManage&&manage,disabled=busy||loading||uncertain||!healthy||!canManage;
  const refs=[draft.singleton,...draft.members];
  const caseExists=!!preview?.issues.some(i=>i.code==='group_case_exists')||!!diagnostic?.issues.some(i=>i.code==='group_case_exists');
  const matchingCase=records.find(r=>relationKey(r.draft)===relationKey(draft));
  const selected=regions.find(r=>r.regionId===selectedRegion);
  const label=(ref:SupplyGroupRef)=>{const d=documents.find(v=>v.documentId===ref.documentId);return d?`${d.latestObservation.approvalNumber||'등록 문서'} · ${d.latestObservation.date} · ${money(d.latestObservation.total)}`:'문서 미선택';};
  const clearPreview=()=>{setPreview(null);setDiagnostic(null);setNotice('');};
  const edit=(fn:(v:Draft)=>Draft)=>{clearPreview();setDraft(fn);};
  const editEvidence=(next:SupplyGroupRegion[])=>{setRegions(next);setDraft(d=>({...d,evidenceManifestId:'',currencyEvidence:[],coverageConfirmed:false}));clearPreview();};
  const showError=(e:unknown)=>{setError(e instanceof Error?e.message:'요청을 처리하지 못했습니다.');setErrorStatus(e instanceof ApiError?e.status:null);setDiagnostic(e instanceof ApiError?e.diagnostic:null);};
  const load=useCallback(async()=>{
    const captured=subjectId,generation=epoch.current;setLoading(true);setHealthy(false);
    try{
      const [list,workspace,catalog]=await Promise.all([json(`${API}?${query(subjectId)}`),json(`/api/finance/supply-reviews?${query(subjectId)}`),json(`${API}?${query(subjectId,{catalog:'documents'})}`)]);
      if(captured!==scope.current||generation!==epoch.current)return;
      checkedList(list);if(!Array.isArray(list.records)||!Array.isArray(workspace.records)||!Array.isArray(catalog.documents))throw Error('목록 응답을 확인할 수 없습니다.');
      setRecords(list.records);setHasMore(!!list.hasMore);setCaseCursor(list.nextCursor);setBasis(workspace.records);setEvidence(workspace.documents);setDocuments(catalog.documents);setDocumentsMore(!!catalog.hasMore);setDocumentCursor(catalog.nextCursor??null);setManage(!!list.canManage);setHealthy(true);
    }catch(e){if(captured===scope.current)showError(e);}finally{if(captured===scope.current)setLoading(false);}
  },[subjectId]);
  useEffect(()=>{epoch.current++;setDraft(blank(subjectId));setOriginal(null);setHistory([]);setHistoryCursor(null);setPreview(null);setRegions([]);setMetadata(null);setEvidenceId('');setError('');setNotice('');setUncertain(false);pending.current=null;void load();return()=>{epoch.current++;};},[subjectId,load]);
  useEffect(()=>{
    setImage('');setImageReady(false);if(!evidenceId||!metadata)return;
    let active=true,url='';const controller=new AbortController();
    void(async()=>{try{const r=await fetch(`${EVIDENCE}?${query(subjectId,{documentId:evidenceId,pageNumber:String(page)})}`,{cache:'no-store',signal:controller.signal});if(!r.ok){const v=await r.json();throw new ApiError(v.error||'PDF를 표시할 수 없습니다.',r.status,null);}if(r.headers.get('content-type')!=='image/png')throw Error('PDF 표시 응답을 확인할 수 없습니다.');url=URL.createObjectURL(await r.blob());if(active)setImage(url);}catch(e){if(active)showError(e);}})();
    return()=>{active=false;controller.abort();if(url)URL.revokeObjectURL(url);};
  },[subjectId,evidenceId,metadata,page]);
  useEffect(()=>{
    setEvidenceDiagnostics(null);setEvidenceDiagnosticError('');if(!draft.evidenceManifestId)return;
    let active=true;void json(`${EVIDENCE}?${query(subjectId,{manifestId:draft.evidenceManifestId})}`).then((v:SupplyGroupEvidenceDiagnostics)=>{if(!active)return;if(v.manifestId!==draft.evidenceManifestId||v.verificationLevel!=='human_review'||!Array.isArray(v.regions)||!Number.isSafeInteger(v.noTextDetailCount)||v.noTextDetailCount!==v.regions.filter(r=>r.role==='detail'&&r.textStatus==='no_text').length)throw Error('원문 추출 안내를 확인할 수 없습니다.');setEvidenceDiagnostics(v);}).catch(e=>{if(active)setEvidenceDiagnosticError(e instanceof Error?e.message:'원문 추출 안내를 확인할 수 없습니다.');});return()=>{active=false;};
  },[subjectId,draft.evidenceManifestId]);
  const run=async(fn:()=>Promise<void>)=>{if(inFlight.current)return;inFlight.current=true;setBusy(true);setError('');setErrorStatus(null);setDiagnostic(null);setNotice('');try{await fn();}catch(e){showError(e);}finally{inFlight.current=false;setBusy(false);}};
  const loadObservations=async(documentId:string)=>{if(!documentId)return;const data=await json(`${DOCUMENTS}?${query(subjectId,{documentId})}`);if(!Array.isArray(data.history))throw Error('문서 관측을 확인할 수 없습니다.');setObservations(old=>({...old,[documentId]:data.history}));setDocuments(old=>[...old,...(data.documents||[]).filter((d:DocumentRow)=>!old.some(v=>v.documentId===d.documentId))]);return data.history as Observation[];};
  const moreDocuments=()=>void run(async()=>{if(!documentCursor)return;const data=await json(`${API}?${query(subjectId,{catalog:'documents',cursor:documentCursor})}`);if(!Array.isArray(data.documents)||(data.hasMore&&typeof data.nextCursor!=='string'))throw Error('다음 문서 목록을 확인할 수 없습니다.');setDocuments(old=>[...old,...data.documents.filter((d:DocumentRow)=>!old.some(v=>v.documentId===d.documentId))]);setDocumentsMore(!!data.hasMore);setDocumentCursor(data.nextCursor??null);});
  const chooseDocument=(index:number,documentId:string)=>void run(async()=>{
    const d=documents.find(v=>v.documentId===documentId),items=await loadObservations(documentId);
    const ref={documentId,portionId:d?.portionId||'',observationId:items?.[0]?.observationId||''};
    edit(v=>({...v,...(index===0?{singleton:ref}:{members:v.members.map((m,i)=>i===index-1?ref:m)}),evidenceManifestId:'',currencyEvidence:[],coverageConfirmed:false}));setRegions([]);
  });
  const chooseEvidence=(documentId:string)=>void run(async()=>{
    setMetadata(null);setEvidenceId(documentId);setPage(1);editEvidence([]);const d=evidence.find(v=>v.documentId===documentId);if(!d)return;
    const result=await json(EVIDENCE,{action:'inspect',subjectId,documentId,evidenceHash:d.evidenceHash});if(!Array.isArray(result.pages)||!Number.isSafeInteger(result.pageCount))throw Error('PDF 페이지를 확인할 수 없습니다.');setMetadata(result);
  });
  const updateRegion=(update:Partial<SupplyGroupRegion>)=>editEvidence(regions.map(r=>r.regionId===selectedRegion?{...r,...update}:r));
  const previewInput=()=>({draft,caseId:original?.caseId??null,expectedVersion:original?.version??0,expectedRevisionId:original?.revisionId??null});
  const inspect=()=>void run(async()=>{setPreview(null);const request=validateGroupPreviewInput(previewInput());const result=await json(API,{action:'preview',...request}) as SupplyGroupPreview;if(result.schemaVersion!=='de1b-group-preview-v1'||result.financialUseSupported!==false||typeof result.canVerify!=='boolean'||!Array.isArray(result.issues)||normalized(result.draft)!==normalized(request.draft))throw Error('미리보기 응답을 확인할 수 없습니다.');setDraft(result.draft);setPreview(result);});
  const open=async(caseId:string,preserve=false)=>{
    const value=checkedList(await json(`${API}?${query(subjectId,{caseId})}`) as List);
    if(!value.records?.length)throw Error('확인 이력을 찾을 수 없습니다.');const rows=[...value.records].sort((a,b)=>b.version-a.version),latest=rows[0];
    setHistory(rows);setHistoryMore(!!value.hasMore);setHistoryCursor(value.nextCursor);setOriginal(latest);setPreview(null);if(!preserve){setDraft(structuredClone(latest.draft));setWithdrawReason('');setRegions([]);setMetadata(null);setEvidenceId('');}
    await Promise.all([latest.draft.singleton,...latest.draft.members].map(r=>loadObservations(r.documentId)));
    if(preserve)setNotice('입력과 철회 사유는 유지했습니다. 최신판을 확인한 뒤 현재 근거 확인 또는 철회를 다시 선택하세요.');
  };
  const moreCases=()=>void run(async()=>{if(!caseCursor)return;const value=checkedList(await json(`${API}?${query(subjectId,{cursor:caseCursor})}`));setRecords(old=>[...old,...value.records.filter(r=>!old.some(v=>v.caseId===r.caseId))]);setHasMore(value.hasMore);setCaseCursor(value.nextCursor);});
  const moreHistory=()=>void run(async()=>{if(!original||!historyCursor)return;const value=checkedList(await json(`${API}?${query(subjectId,{caseId:original.caseId,cursor:historyCursor})}`));if(value.records.some(r=>r.caseId!==original.caseId))throw Error('선택한 사건의 이력을 확인할 수 없습니다.');setHistory(old=>[...old,...value.records.filter(r=>!old.some(v=>v.revisionId===r.revisionId))]);setHistoryMore(value.hasMore);setHistoryCursor(value.nextCursor);});
  const save=(action:Pending['action'],retry=false)=>void run(async()=>{
    if(!retry){
      if(action==='register'){const d=evidence.find(v=>v.documentId===evidenceId);if(!d||!imageReady)return;pending.current={endpoint:EVIDENCE,action,body:{action,subjectId,documentId:d.documentId,evidenceHash:d.evidenceHash,regions,requestId:`sge-${crypto.randomUUID()}`}};}
      else if(action==='verify'){if(!preview?.canVerify)return;pending.current={endpoint:API,action,body:{action,...previewInput(),expectedPreviewHash:preview.previewHash,requestId:`sgr-${crypto.randomUUID()}`}};}
      else{if(!original||original.state!=='verified_group'||!withdrawReason.trim())return;pending.current={endpoint:API,action,body:{action,subjectId,caseId:original.caseId,expectedVersion:original.version,expectedRevisionId:original.revisionId,reason:withdrawReason.trim(),requestId:`sgr-${crypto.randomUUID()}`}};}
    }
    const attempt=pending.current;if(!attempt)return;
    try{
      const result=await json(attempt.endpoint,attempt.body);
      if(attempt.action==='register'){if(typeof result.manifestId!=='string'||result.verificationLevel!=='human_review'||typeof result.replayed!=='boolean')throw Error('근거 저장 결과를 확인할 수 없습니다.');setDraft(v=>({...v,evidenceManifestId:result.manifestId}));setNotice('원문 위치 근거를 보관했습니다. 문서별 통화 위치와 전체 대응을 확인하세요.');}
      else{if(result.financialUseSupported!==false||typeof result.caseId!=='string'||typeof result.replayed!=='boolean')throw Error('확인 저장 결과를 확인할 수 없습니다.');await load();await open(result.caseId);setNotice(`${result.replayed?'이미 처리된 요청의 결과를 확인했습니다.':result.state==='withdrawn'?'철회 판을 남겼습니다.':'전체 대응 관계를 확인했습니다.'} 전표·부가세·납부에는 반영되지 않습니다.`);}
      pending.current=null;setUncertain(false);setPreview(null);
    }catch(e){if(e instanceof ApiError&&[400,403,404,409].includes(e.status)){pending.current=null;setUncertain(false);setPreview(null);}else setUncertain(true);throw e;}
  });
  const download=()=>{const blob=new Blob([JSON.stringify({financialUseSupported:false,historicalRecords:history,hasMore:historyMore},null,2)],{type:'application/json;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='여러문서_전체대응_확인이력.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  const position=(event:React.PointerEvent<HTMLDivElement>)=>{const box=event.currentTarget.getBoundingClientRect();return{x:Math.max(0,Math.min(1,(event.clientX-box.left)/box.width)),y:Math.max(0,Math.min(1,(event.clientY-box.top)/box.height))};};
  return <section className="rounded-lg border cd-border-c p-4 space-y-4" aria-label="여러 문서 전체의 공급 대응">
    <div className="flex flex-wrap items-start justify-between gap-2"><div className="flex items-center gap-2"><h3 className="font-semibold cd-text">여러 문서 전체의 공급 대응</h3><CdHelp label="전체 대응 도움말"><p>기준 문서 한 장의 전체가 여러 문서 전체와 대응하는지 원문을 보고 확인합니다. 합계만 같다는 이유로 같은 공급이 되지는 않습니다.</p><p className="mt-2">PDF 표시와 담당자 확인을 보관합니다. 문서 진위·공제 가능 여부를 자동 검증하지 않습니다. 일부 금액 분할과 취소액 상계는 지원하지 않습니다.</p></CdHelp></div><span className="cd-pill cd-pill-idle">금융 반영 없음</span></div>
    <p className="text-sm cd-text-muted">확인·철회는 전표·부가세·납부를 바꾸지 않습니다.</p>
    {error&&<div role="alert" className="rounded-lg border cd-border-c p-3 text-sm cd-error-text"><p>{error}</p>{diagnostic?.issues.length? <ul className="mt-2 list-disc pl-5">{diagnostic.issues.map((v,i)=><li key={`${v.code}:${i}`}>{v.message}</li>)}</ul>:null}{diagnostic?.issuesTruncated&&<p>전체 {diagnostic.totalIssueCount}개 중 20개를 표시합니다.</p>}<p className="mt-2">{uncertain?'처리 결과가 불확실합니다. 같은 요청을 재확인하세요.':errorStatus===403?'이 작업 권한이 있는 담당자에게 확인하세요.':diagnostic?.nextAction==='reload_latest'?'최신 확인판을 불러온 뒤 작업을 다시 선택하세요.':'입력은 유지됩니다. 보완한 뒤 현재 근거를 다시 확인하세요.'}</p>{original&&!uncertain&&errorStatus!==403&&<button type="button" className="cd-btn cd-btn-sm mt-2" disabled={busy} onClick={()=>void run(()=>open(original.caseId,true))}>입력을 유지하고 최신판 불러오기</button>}</div>}
    {caseExists&&<div className="border cd-border-c rounded-lg p-3 space-y-2"><p className="text-sm cd-text">같은 문서 집합의 기존 사건이 있습니다. 작성 중 입력을 유지한 채 기존 사건의 최신판으로 이어서 검토하세요.</p>{matchingCase?<button type="button" className="cd-btn" disabled={busy||uncertain} onClick={()=>void run(()=>open(matchingCase.caseId,true))}>이 문서 집합의 기존 사건 열기</button>:<button type="button" className="cd-btn" onClick={()=>caseList.current?.scrollIntoView({behavior:'smooth',block:'start'})}>기존 사건 목록에서 찾기</button>}</div>}
    {notice&&<p role="status" className="text-sm cd-text">{notice}</p>}
    {loading&&<p className="text-sm cd-text-muted">원문과 검토 목록을 읽고 있습니다.</p>}
    {!loading&&!healthy&&<button type="button" className="cd-btn" onClick={()=>void load()}>목록 다시 읽기</button>}
    {healthy&&canManage&&<div className="space-y-4">
      <CdSelect label="전체 대응의 원천 기록" value={draft.reviewRevisionId} disabled={disabled} onChange={e=>edit(v=>({...v,reviewRevisionId:e.target.value,coverageConfirmed:false}))}><option value="">기록 선택</option>{draft.reviewRevisionId&&!basis.some(r=>r.state!=='withdrawn'&&r.revisionId===draft.reviewRevisionId)&&<option value={draft.reviewRevisionId}>이 사건에 보관된 원천 기록</option>}{basis.filter(r=>r.state!=='withdrawn').map(r=><option key={r.revisionId} value={r.revisionId}>{r.draft.title} · {r.version}판</option>)}</CdSelect>
      <div className="grid gap-3 md:grid-cols-2">{refs.map((ref,index)=><fieldset key={index} className="min-w-0 rounded-lg border cd-border-c p-3 space-y-2"><legend className="text-sm px-1 cd-text">{index===0?'기준 문서 전체':`구성 문서 ${index} 전체`}</legend><CdSelect label={index===0?'기준 등록 문서':`구성 ${index} 등록 문서`} value={ref.documentId} disabled={disabled||!!original} onChange={e=>chooseDocument(index,e.target.value)}><option value="">문서 선택</option>{documents.map(d=><option key={d.documentId} value={d.documentId}>{d.latestObservation.approvalNumber||'등록 문서'} · {d.latestObservation.date} · {money(d.latestObservation.total)}</option>)}</CdSelect><CdSelect label={index===0?'기준 관측 판':`구성 ${index} 관측 판`} value={ref.observationId} disabled={disabled||!ref.documentId} onChange={e=>{const next={...ref,observationId:e.target.value};edit(v=>({...v,...(index===0?{singleton:next}:{members:v.members.map((m,i)=>i===index-1?next:m)}),evidenceManifestId:'',currencyEvidence:[],coverageConfirmed:false}));setRegions([]);}}><option value="">관측 선택</option>{(observations[ref.documentId]||[]).map(o=><option key={o.observationId} value={o.observationId}>{o.version}판 · {o.summary.date} · {money(o.summary.total)}</option>)}</CdSelect>{index>0&&draft.members.length>2&&!original&&<button type="button" className="cd-btn cd-btn-sm" disabled={disabled} onClick={()=>{edit(v=>({...v,members:v.members.filter((_,i)=>i!==index-1),evidenceManifestId:'',currencyEvidence:[],coverageConfirmed:false}));setRegions([]);}}>구성 {index} 삭제</button>}</fieldset>)}</div>
      {!original&&<button type="button" className="cd-btn" disabled={disabled||draft.members.length>=20} onClick={()=>edit(v=>({...v,members:[...v.members,blankRef()],evidenceManifestId:'',coverageConfirmed:false}))}>구성 문서 추가</button>}
      {documentsMore&&<div className="space-y-2"><p className="text-sm cd-text-muted">아직 표시하지 않은 등록 문서가 있습니다.</p><button type="button" className="cd-btn" disabled={disabled} onClick={moreDocuments}>등록 문서 더 불러오기</button></div>}
      <div className="rounded-lg border cd-border-c p-3 space-y-3"><h4 className="font-semibold cd-text">PDF 원문 위치 확인</h4><p className="text-sm cd-text-muted">10 MiB·20페이지 이내 PDF를 표시합니다. 글자가 추출되지 않는 스캔도 원문을 보고 확인할 수 있습니다.</p>
        <CdSelect label="전체 대응 PDF 증빙" value={evidenceId} disabled={disabled} onChange={e=>chooseEvidence(e.target.value)}><option value="">보관 PDF 선택</option>{evidence.filter(e=>e.contentType==='application/pdf'||e.fileName.toLowerCase().endsWith('.pdf')).map(e=><option key={e.documentId} value={e.documentId}>{e.fileName}</option>)}</CdSelect>
        {metadata&&<><CdSelect label="PDF 페이지" value={page} disabled={disabled} onChange={e=>setPage(Number(e.target.value))}>{metadata.pages.map(p=><option key={p.pageNumber} value={p.pageNumber}>{p.pageNumber}쪽{p.rotation?` · ${p.rotation}° 회전`:''}</option>)}</CdSelect>
          {image?<div className="relative max-w-3xl border cd-border-c bg-white select-none" style={{touchAction:selected&&!disabled?'none':'auto'}} onPointerDown={e=>{if(disabled||!selected||!imageReady)return;drag.current=position(e);e.currentTarget.setPointerCapture(e.pointerId);}} onPointerUp={e=>{if(!drag.current||!selected)return;const end=position(e),start=drag.current;drag.current=null;const x=Math.min(start.x,end.x),y=Math.min(start.y,end.y),width=Math.abs(start.x-end.x),height=Math.abs(start.y-end.y);if(width>.001&&height>.001)updateRegion({pageNumber:page,rect:{x,y,width:Math.min(width,1-x),height:Math.min(height,1-y)}});}}><img src={image} alt={`보관 원문 ${page}쪽`} className="block w-full h-auto" draggable={false} onLoad={()=>setImageReady(true)} onError={()=>{setImageReady(false);setError('PDF 표시를 완료하지 못했습니다.');}}/>{regions.filter(r=>r.pageNumber===page).map(r=><div key={r.regionId} className="absolute pointer-events-none border-2 border-blue-600 bg-blue-500/10" style={{left:`${r.rect.x*100}%`,top:`${r.rect.y*100}%`,width:`${r.rect.width*100}%`,height:`${r.rect.height*100}%`}}><span className="text-xs bg-white text-black">영역 {regions.indexOf(r)+1}</span></div>)}</div>:<p className="text-sm cd-text-muted">PDF 원문을 표시하고 있습니다.</p>}
          <button type="button" className="cd-btn" disabled={disabled||!imageReady||regions.length>=64||refs.some(r=>!r.observationId)} onClick={()=>{const r:SupplyGroupRegion={regionId:`region-${crypto.randomUUID()}`,pageNumber:page,rect:{x:0,y:0,width:1,height:1},role:'detail',wholeRefs:[]};editEvidence([...regions,r]);setSelectedRegion(r.regionId);}}>원문 영역 추가</button>
          {regions.length>0&&<CdSelect label="편집할 원문 영역" value={selectedRegion} disabled={disabled} onChange={e=>{setSelectedRegion(e.target.value);const r=regions.find(r=>r.regionId===e.target.value);if(r)setPage(r.pageNumber);}}>{regions.map((r,i)=><option key={r.regionId} value={r.regionId}>영역 {i+1} · {r.pageNumber}쪽</option>)}</CdSelect>}
          {selected&&<fieldset className="border cd-border-c rounded-lg p-3 space-y-3"><legend className="text-sm cd-text px-1">선택 영역</legend><p className="text-sm cd-text-muted">원문에서 드래그하거나 아래 비율을 입력하세요. 제목·단위는 공통 근거로, 구성 문서의 거래 행은 세부 근거로 구분합니다.</p><CdSelect label="영역의 용도" value={selected.role} disabled={disabled} onChange={e=>updateRegion({role:e.target.value as 'context'|'detail'})}><option value="context">공통 제목·단위·전체 설명</option><option value="detail">구성 문서의 세부 근거</option></CdSelect><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{(['x','y','width','height'] as const).map(k=><label key={k} className="text-sm cd-text space-y-1"><span>{{x:'왼쪽 (%)',y:'위쪽 (%)',width:'넓이 (%)',height:'높이 (%)'}[k]}</span><input type="number" min="0" max="100" step="0.1" className="cd-input w-full" value={Number((selected.rect[k]*100).toFixed(4))} disabled={disabled} onChange={e=>updateRegion({rect:{...selected.rect,[k]:Number(e.target.value)/100}})}/></label>)}</div><fieldset className="space-y-2"><legend className="text-sm cd-text">이 영역이 뒷받침하는 문서</legend>{refs.map((ref,i)=><label key={i} className="flex gap-2 text-sm cd-text"><input type="checkbox" disabled={disabled||!ref.observationId} checked={selected.wholeRefs.some(w=>w.documentId===ref.documentId)} onChange={e=>updateRegion({wholeRefs:e.target.checked?[...selected.wholeRefs,ref]:selected.wholeRefs.filter(w=>w.documentId!==ref.documentId)})}/><span>{i===0?'기준':`구성 ${i}`} · {label(ref)}</span></label>)}</fieldset><button type="button" className="cd-btn cd-btn-sm" disabled={disabled} onClick={()=>{editEvidence(regions.filter(r=>r.regionId!==selectedRegion));setSelectedRegion('');}}>선택 영역 삭제</button></fieldset>}
          <button type="button" className="cd-btn" disabled={disabled||!imageReady||!regions.length||regions.some(r=>!r.wholeRefs.length)} onClick={()=>save('register')}>원문 위치 근거 보관</button>
        </>}
        {draft.evidenceManifestId&&<p role="status" className="text-sm cd-text">원문 위치 근거가 보관되어 있습니다. 실제 공급과 내용 해석은 담당자 검토입니다.</p>}
      </div>
      {draft.evidenceManifestId&&regions.length>0&&<fieldset className="space-y-3"><legend className="font-semibold cd-text">문서별 원화 표시 위치</legend>{refs.map((ref,i)=><CdSelect key={i} label={`${i===0?'기준':`구성 ${i}`} 문서 통화 근거`} value={draft.currencyEvidence.find(c=>c.documentId===ref.documentId)?.manifestRegionId||''} disabled={disabled} onChange={e=>edit(v=>({...v,currencyEvidence:[...v.currencyEvidence.filter(c=>c.documentId!==ref.documentId),{documentId:ref.documentId,currency:'KRW',manifestRegionId:e.target.value}]}))}><option value="">원화 표시가 있는 영역 선택</option>{regions.filter(r=>r.wholeRefs.some(w=>w.documentId===ref.documentId)).map(r=><option key={r.regionId} value={r.regionId}>영역 {regions.indexOf(r)+1} · {r.pageNumber}쪽</option>)}</CdSelect>)}</fieldset>}
      {evidenceDiagnostics&&evidenceDiagnostics.noTextDetailCount>0&&<aside className="rounded-lg border cd-border-c p-3 space-y-2" aria-label="원문 글자 추출 안내"><p className="text-sm cd-text">선택한 세부 영역 {evidenceDiagnostics.noTextDetailCount}곳에서 글자를 추출하지 못했습니다.</p><p className="text-sm cd-text-muted">스캔이거나 선택 위치가 빈 곳일 수 있습니다. 표시된 원문과 영역이 맞는지 확인하세요. 이 안내는 스캔본의 검토를 차단하지 않습니다.</p><ul className="text-sm cd-text-muted list-disc pl-5">{evidenceDiagnostics.regions.map((r,i)=>r.role==='detail'&&r.textStatus==='no_text'?<li key={r.regionId}>{r.pageNumber}쪽 · 영역 {i+1}</li>:null)}</ul></aside>}
      {evidenceDiagnosticError&&<p role="alert" className="text-sm cd-error-text">{evidenceDiagnosticError} 원문 추출 상태를 정상으로 확인한 것은 아닙니다.</p>}
      <label className="block text-sm cd-text space-y-1"><span>전체 대응을 확인한 이유</span><textarea aria-label="전체 대응을 확인한 이유" className="cd-input w-full min-h-24" value={draft.reason} maxLength={2000} disabled={disabled} onChange={e=>edit(v=>({...v,reason:e.target.value}))}/></label>
      <label className="flex items-start gap-2 text-sm cd-text"><input type="checkbox" checked={draft.coverageConfirmed} disabled={disabled} onChange={e=>edit(v=>({...v,coverageConfirmed:e.target.checked}))}/><span>원문을 보고 기준·구성 문서 전체가 대응하며 구성 문서가 중복되지 않음을 확인했습니다.</span></label>
      <button type="button" className="cd-btn cd-btn-primary" disabled={disabled||!draft.coverageConfirmed||!draft.evidenceManifestId} onClick={inspect}>현재 전체 대응 근거 확인</button>
      {preview&&<section className="space-y-3 border cd-border-c rounded-lg p-3" aria-label="현재 전체 대응 진단"><p className="font-semibold cd-text">{preview.canVerify?'확인 기록을 남길 수 있습니다.':'정보 보완이 필요합니다.'}</p>{preview.issues.length>0&&<ul className="text-sm cd-error-text list-disc pl-5">{safeGroupIssues(preview.issues).slice(0,20).map((v,i)=><li key={`${v.code}:${i}`}>{v.message}</li>)}</ul>}{preview.issues.length>20&&<p className="text-sm cd-text-muted">전체 {preview.issues.length}개 중 20개를 표시합니다.</p>}<div className="text-sm cd-text">{[preview.singleton,...preview.members].map((s,i)=><p key={i}>{i===0?'기준':`구성 ${i}`}: {s?`공급가액 ${money(s.supply)} · 세액 ${money(s.tax)} · 합계 ${money(s.total)}`:'원천 미확인'}</p>)}</div>{preview.canVerify&&<button type="button" className="cd-btn cd-btn-primary" disabled={disabled} onClick={()=>save('verify')}>전체 대응 관계 확인</button>}<p className="text-sm cd-text-muted">금융 반영 없음 · 공제 가능 여부나 원문 진위의 자동 판정이 아닙니다.</p></section>}
      {original?.state==='verified_group'&&<div className="space-y-2"><label className="block text-sm cd-text space-y-1"><span>전체 대응 철회 사유</span><textarea aria-label="전체 대응 철회 사유" className="cd-input w-full" value={withdrawReason} maxLength={2000} disabled={disabled} onChange={e=>setWithdrawReason(e.target.value)}/></label><button type="button" className="cd-btn" disabled={disabled||!withdrawReason.trim()} onClick={()=>save('withdraw')}>전체 대응 확인 철회</button></div>}
      {uncertain&&<div className="space-y-2"><p className="text-sm cd-text">응답을 확인하지 못했습니다. 입력을 바꾸지 않고 같은 요청의 결과를 확인합니다.</p><button type="button" className="cd-btn cd-btn-primary" disabled={busy||loading} onClick={()=>save(pending.current?.action||'verify',true)}>같은 {pending.current?.action==='withdraw'?'철회':pending.current?.action==='register'?'원문 보관':'확인'} 요청 재확인</button></div>}
      {original&&!uncertain&&<button type="button" className="cd-btn" disabled={busy} onClick={()=>{setOriginal(null);setDraft(blank(subjectId));setPreview(null);setHistory([]);setRegions([]);setEvidenceId('');setMetadata(null);}}>새 문서 집합 작성</button>}
    </div>}
    {healthy&&<section ref={caseList} className="space-y-3" aria-label="전체 대응 이력 목록"><h4 className="font-semibold cd-text">전체 대응 확인 이력</h4>{records.length?<div className="overflow-x-auto"><table className="cd-table w-full text-sm"><thead><tr><th>검토한 문서 집합</th><th>당시 상태</th><th>구성 문서</th><th>판</th><th>보기</th></tr></thead><tbody>{records.filter((r,i)=>records.findIndex(x=>x.caseId===r.caseId)===i).map(r=><tr key={r.caseId} className="h-11"><td className="max-w-64"><p>{r.preview.singleton?.date||'기준일 확인 필요'} · {r.preview.singleton?money(r.preview.singleton.total):'기준 금액 확인 필요'}</p><p className="truncate cd-text-muted" title={r.draft.reason}>{r.draft.reason}</p></td><td>{state(r)}</td><td>{r.draft.members.length}개</td><td>{r.version}판</td><td><button type="button" className="cd-btn cd-btn-sm" disabled={busy||uncertain} onClick={()=>void run(()=>open(r.caseId))}>전체 대응 이력 보기</button></td></tr>)}</tbody></table></div>:<p className="text-sm cd-text-muted">아직 전체 대응 확인 이력이 없습니다.</p>}{hasMore&&<div className="space-y-2"><p className="text-sm cd-text-muted">아직 불러오지 않은 사건이 있습니다.</p><button type="button" className="cd-btn" disabled={busy||loading||uncertain} onClick={moreCases}>이전 사건 더 보기</button></div>}</section>}
    {healthy&&!canManage&&<>
      {evidenceDiagnostics&&evidenceDiagnostics.noTextDetailCount>0&&<aside className="rounded-lg border cd-border-c p-3 space-y-2" aria-label="원문 글자 추출 안내"><p className="text-sm cd-text">선택한 세부 영역 {evidenceDiagnostics.noTextDetailCount}곳에서 글자를 추출하지 못했습니다.</p><p className="text-sm cd-text-muted">스캔이거나 선택 위치가 빈 곳일 수 있습니다. 표시된 원문과 영역이 맞는지 확인하세요. 이 안내는 스캔본의 검토를 차단하지 않습니다.</p><ul className="text-sm cd-text-muted list-disc pl-5">{evidenceDiagnostics.regions.map((r,i)=>r.role==='detail'&&r.textStatus==='no_text'?<li key={r.regionId}>{r.pageNumber}쪽 · 영역 {i+1}</li>:null)}</ul></aside>}
      {evidenceDiagnosticError&&<p role="alert" className="text-sm cd-error-text">{evidenceDiagnosticError} 원문 추출 상태를 정상으로 확인한 것은 아닙니다.</p>}
    </>}
    {history.length>0&&<section className="rounded-lg border cd-border-c p-3 space-y-3" aria-label="당시 전체 대응 확인판"><div className="flex justify-between gap-2"><h4 className="font-semibold cd-text">당시 전체 대응 확인판</h4><button type="button" className="cd-btn cd-btn-sm" onClick={download}>전체 대응 이력 내려받기</button></div><p className="text-sm cd-text-muted">현재 유효성이나 공제 가능 여부를 보증하지 않는 당시 기록입니다. 금융 반영 없음.</p>{history.map(r=><article key={r.revisionId} className="border-t cd-border-c pt-2 text-sm cd-text"><p>{r.version}판 · {state(r)} · {new Date(r.createdAt).toLocaleString('ko-KR')}</p><p className="break-words">{r.withdrawalReason||r.draft.reason}</p></article>)}{historyMore&&<div className="space-y-2"><p className="text-sm cd-text-muted">불러온 {history.length}판을 표시합니다. 이전 판이 더 있습니다. 내려받기에는 불러온 판만 포함됩니다.</p><button type="button" className="cd-btn" disabled={busy||loading||uncertain} onClick={moreHistory}>이전 판 더 보기</button></div>}</section>}
  </section>;
}
