import { formatBarobillDT } from '@/lib/barobill/client';
import type { SupplySameDraft, SupplySamePreviewInput, SupplySameSaveInput, SupplySameWithdrawInput, SupplySameTimeDiagnostic } from './supply-same-types';
export const sameError = (message: string, status = 400, code = 'supply_same_input') => Object.assign(new Error(message), { status, code });
export const sameUnavailable = () => sameError('동일 공급 확인의 자료구조 또는 보관 근거를 확인할 수 없습니다.', 503, 'supply_same_unavailable');
const obj = (v: unknown): Record<string, unknown> => { if (!v || typeof v !== 'object' || Array.isArray(v)) throw sameError('입력 형식을 확인하세요.'); return v as Record<string, unknown>; };
const keys = (v: Record<string, unknown>, names: string[]) => { if (Object.keys(v).length !== names.length || names.some(n => !Object.hasOwn(v, n))) throw sameError('지원하지 않거나 누락된 입력입니다.'); };
export const sameId = (v: unknown): string => { if (typeof v !== 'string' || !v.length || v.length > 200 || v.trim() !== v || /[\x00-\x1f\x7f]/.test(v)) throw sameError('식별자를 확인하세요.'); return v; };
const longText = (v: unknown): string => { if (typeof v !== 'string' || !v.trim() || v.length > 2000 || /[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]/.test(v)) throw sameError('이유와 증빙 위치를 입력하세요.'); return v; };
const digest = (v: unknown): string => { if (typeof v !== 'string' || !/^[a-f0-9]{64}$/.test(v)) throw sameError('근거 해시를 확인하세요.'); return v; };
const version = (v: unknown): number => { if (!Number.isSafeInteger(v) || Number(v) < 0 || Number(v) > 2147483646) throw sameError('판 번호를 확인하세요.'); return Number(v); };
function draft(v: unknown): SupplySameDraft { const d=obj(v); keys(d,['subjectId','reviewRevisionId','left','right','reason','evidence']); const ref=(x:unknown)=>{const r=obj(x);keys(r,['documentId','portionId','observationId']);return {documentId:sameId(r.documentId),portionId:sameId(r.portionId),observationId:sameId(r.observationId)};}; const e=obj(d.evidence);keys(e,['documentId','evidenceHash','location']);return {subjectId:sameId(d.subjectId),reviewRevisionId:sameId(d.reviewRevisionId),left:ref(d.left),right:ref(d.right),reason:longText(d.reason),evidence:{documentId:sameId(e.documentId),evidenceHash:digest(e.evidenceHash),location:longText(e.location)}}; }
export function validateSamePreviewInput(v: unknown, save: true): SupplySameSaveInput;
export function validateSamePreviewInput(v: unknown, save?: false): SupplySamePreviewInput;
export function validateSamePreviewInput(v: unknown, save=false): SupplySamePreviewInput | SupplySameSaveInput { const p=obj(v); keys(p,['draft','caseId','expectedVersion','expectedRevisionId',...(save?['expectedPreviewHash','requestId']:[])]);const n=version(p.expectedVersion), c=p.caseId===null?null:sameId(p.caseId), r=p.expectedRevisionId===null?null:sameId(p.expectedRevisionId);if ((n===0)!==(c===null&&r===null) || n>0&&(c===null||r===null)) throw sameError('현재 확인판을 선택하세요.');const result={draft:draft(p.draft),caseId:c,expectedVersion:n,expectedRevisionId:r};return save?{...result,expectedPreviewHash:digest(p.expectedPreviewHash),requestId:sameId(p.requestId)}:result; }
export function validateSameWithdraw(v:unknown):SupplySameWithdrawInput {const p=obj(v);keys(p,['subjectId','caseId','expectedVersion','expectedRevisionId','reason','requestId']);const n=version(p.expectedVersion);if(!n)throw sameError('철회할 확인판을 선택하세요.');return {subjectId:sameId(p.subjectId),caseId:sameId(p.caseId),expectedVersion:n,expectedRevisionId:sameId(p.expectedRevisionId),reason:longText(p.reason),requestId:sameId(p.requestId)};}
/** Collection projection compatibility is separate from sufficient, valid time evidence. */
export function diagnoseSameCardTime(sourceId: string, raw: unknown, stored: unknown): SupplySameTimeDiagnostic { const safe=(v:unknown):string|null=>typeof v==='string'&&v.length<=80&&/^[0-9TZ +:.\-]+$/.test(v)?v:null;const rawValue=safe(raw), storedValue=safe(stored);const projectedValue=rawValue===null?null:formatBarobillDT(rawValue);const projectionMatches=projectedValue===null||storedValue===null?null:projectedValue===storedValue;const accepted=rawValue!==null&&(/^[0-9]{14}$/.test(rawValue)||/^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}$/.test(rawValue));const valid=(s:string|null)=>{if(!s||!/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$/.test(s)||Number(s.slice(0,4))<1000)return false;const d=new Date(s.replace(' ','T')+'Z');return !Number.isNaN(d.getTime())&&d.toISOString().slice(0,19).replace('T',' ')===s;};const evidenceSufficient=accepted&&valid(projectedValue)&&valid(storedValue);return {sourceId,version:'card-approval-time-evidence-v1',rawValue,projectedValue,storedValue,projectionMatches,evidenceSufficient,status:!evidenceSufficient?'unavailable':projectionMatches?'matched':'conflict'}; }
