import { rowsToObjects, withDbRead, withDbWrite, type PgDatabase } from '@/lib/db';
import { recordAuditLogInline } from '@/lib/auth/audit';
import { lockAccountingWrite } from './write-lock';
import { assertSupplySamePrerequisites } from './supply-same-prerequisites';
import { readRecognitionSubjects } from './recognition-review-subjects';
import { strictRecognitionSubject } from './recognition-review-pure';
import { requireVatFilingDocument } from './vat-filing-documents';
import { sameCurrentPreviewError } from './supply-same-diagnostics';
import { sameId, sameError, sameUnavailable, validateSamePreviewInput, validateSameWithdraw } from './supply-same-pure';
import type { SupplySamePreviewInput, SupplySameSaveInput, SupplySameWithdrawInput, SupplySamePreview, SupplySameResult, SupplySameList } from './supply-same-types';

function failure(error: unknown): never { const e=error as {status?:number;code?:string};if([400,403,404,409,503].includes(e.status??0))throw error;if(['23503','23505','23514','40001','40P01'].includes(e.code??''))throw sameError('근거 또는 최신 확인판이 바뀌었습니다. 다시 확인하세요.',409,'supply_same_conflict');if(e.code==='22023')throw sameError('동일 공급 확인 입력을 확인하세요.');throw sameUnavailable(); }
async function transaction<T>(write:boolean,fn:(db:PgDatabase)=>Promise<T>):Promise<T> {for(let attempt=0;;attempt++){try{const work=async(db:PgDatabase)=>{if(write)await lockAccountingWrite(db);await assertSupplySamePrerequisites(db,process.env.FINANCE_R1_SCHEMA??'public');return fn(db);};return write?await withDbWrite(work):await withDbRead(work);}catch(e){if(attempt<2&&['40001','40P01'].includes(String((e as {code?:string}).code)))continue;return failure(e);}}}
function resultValue<T>(r:Awaited<ReturnType<PgDatabase['exec']>>):T {const v=r[0]?.values[0]?.[0];if(v===undefined||v===null)throw sameUnavailable();return(typeof v==='string'?JSON.parse(v):v) as T;}
function validResult(v:SupplySameResult):SupplySameResult {if(!v||v.financialUseSupported!==false||!['verified_same','withdrawn'].includes(v.state)||!Number.isSafeInteger(v.version)||v.version<1||typeof v.replayed!=='boolean')throw sameUnavailable();for(const id of [v.caseId,v.revisionId]){try{sameId(id);}catch{throw sameUnavailable();}}return v;}
function validPreview(v:SupplySamePreview):SupplySamePreview {if(!v||v.schemaVersion!=='de1b-whole-preview-v1'||v.financialUseSupported!==false||typeof v.canVerify!=='boolean'||!Array.isArray(v.issues)||!Array.isArray(v.timeDiagnostics)||!/^[a-f0-9]{64}$/.test(v.previewHash)||v.canVerify!==(v.issues.length===0))throw sameUnavailable();for(const s of [v.left,v.right])if(s&&(![s.supply,s.tax,s.total].every(Number.isSafeInteger)||s.supply+s.tax!==s.total))throw sameUnavailable();return v;}
async function requireSubject(db:PgDatabase,subjectId:string){if(!rowsToObjects(await db.exec('SELECT subject_id FROM vat_filing_subjects WHERE subject_id=$1',[subjectId])).length)throw sameError('회사 기준을 찾을 수 없습니다.',404,'supply_same_subject_missing');}
async function evidence(db:PgDatabase,p:SupplySamePreview){await requireSubject(db,p.draft.subjectId);const doc=await requireVatFilingDocument(p.draft.evidence.documentId,p.draft.subjectId,db);if(doc.evidenceHash!==p.draft.evidence.evidenceHash)throw sameError('선택한 보관 증빙 해시가 다릅니다.',409,'supply_same_document_changed');const subjects=await readRecognitionSubjects(db),collector=process.env.BAROBILL_CORPNUM;for(const date of new Set([p.left?.date,p.right?.date].filter((v):v is string=>!!v))){const s=strictRecognitionSubject(subjects,p.draft.subjectId,date,collector,collector);if(!s.evidenceRef?.startsWith('vat-document:')||!s.evidenceHash)throw sameError('해당일 회사 근거가 부족합니다.',409,'supply_same_subject_changed');const proof=await requireVatFilingDocument(s.evidenceRef.slice(13),p.draft.subjectId,db);if(proof.evidenceHash!==s.evidenceHash)throw sameUnavailable();}}
async function preview(db:PgDatabase,value:SupplySamePreviewInput){const p=validPreview(resultValue<SupplySamePreview>(await db.exec('SELECT finance_same_preview($1::jsonb)',[JSON.stringify(value)])));await evidence(db,p);return p;}
export async function previewSupplySame(input:unknown):Promise<SupplySamePreview>{const value=validateSamePreviewInput(input);return transaction(false,db=>preview(db,value));}
async function replay(value:SupplySameSaveInput|SupplySameWithdrawInput,action:string,actor:string):Promise<SupplySameResult|null>{return transaction(false,async db=>{const q=rowsToObjects(await db.exec('SELECT actor_user_id,action,payload_json=$2::jsonb AS input_matches,result_json FROM finance_same_requests WHERE request_id=$1',[value.requestId,JSON.stringify(value)]))[0];if(!q)return null;if(q.actor_user_id!==actor||q.action!==action||q.input_matches!==true)throw sameError('이미 처리된 요청의 담당자나 내용이 다릅니다.',409,'supply_same_request_conflict');try{await db.exec('SELECT finance_same_assert_request($1)',[value.requestId]);}catch(e){if(['40001','40P01'].includes(String((e as {code?:string}).code)))throw e;throw sameUnavailable();}return{...validResult(q.result_json as SupplySameResult),replayed:true};});}
async function write(value:SupplySameSaveInput|SupplySameWithdrawInput,action:'verify'|'withdraw',actor:string){const completed=await replay(value,action,actor);if(completed)return completed;return transaction(true,async db=>{await db.exec('SELECT finance_same_lock()');const old=rowsToObjects(await db.exec('SELECT request_id FROM finance_same_requests WHERE request_id=$1',[value.requestId]));if(!old.length&&action==='verify'){const {requestId:_,expectedPreviewHash,...p}=value as SupplySameSaveInput;const now=await preview(db,p);const conflict=sameCurrentPreviewError(now,expectedPreviewHash);if(conflict)throw conflict;}const result=validResult(resultValue<SupplySameResult>(await db.exec('SELECT finance_same_write($1,$2::jsonb,$3,$4)',[action,JSON.stringify(value),value.requestId,actor])));if(!result.replayed)await recordAuditLogInline(db,{actorUserId:actor,action:'finance_supply_same_review',targetTable:'finance_same_revisions',targetId:result.revisionId,after:result});return result;});}
export async function verifySupplySame(input:unknown,actorUserId:string):Promise<SupplySameResult>{return write(validateSamePreviewInput(input,true),'verify',sameId(actorUserId));}
export async function withdrawSupplySame(input:unknown,actorUserId:string):Promise<SupplySameResult>{return write(validateSameWithdraw(input),'withdraw',sameId(actorUserId));}
export async function listSupplySame(subjectId:string,caseId?:string,cursor?:string):Promise<SupplySameList>{const subject=sameId(subjectId),id=caseId===undefined?null:sameId(caseId),after=cursor===undefined?null:sameId(cursor);return transaction(false,async db=>{await requireSubject(db,subject);const list=resultValue<SupplySameList>(await db.exec('SELECT finance_same_list($1,$2,$3)',[subject,id,after]));if(!list||!Array.isArray(list.records)||typeof list.hasMore!=='boolean'||list.hasMore!==(typeof list.nextCursor==='string'&&list.nextCursor.length>0)||!list.hasMore&&list.nextCursor!==null)throw sameUnavailable();for(const r of list.records){validResult({...r,replayed:false});validPreview(r.preview);if(r.draft.subjectId!==subject||id!==null&&r.caseId!==id)throw sameUnavailable();}return list;});}
